import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/components/common/Sidebar";
import { adminProxy } from "@/lib/adminProxy";
import { AuthProvider } from "@/contexts/AuthContext";
import { redirect } from "next/navigation";
import "../globals.css";

export const dynamic = "force-dynamic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dashboard - Admin Panel",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { allowed } = await adminProxy();

  if (!allowed) {
    redirect("/");
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-screen antialiased overflow-hidden`}
    >
      <body className="h-screen text-foreground overflow-hidden">
        <AuthProvider>
          <div className="h-screen flex">
            <Sidebar />
            <main className="flex-1 overflow-y-auto overflow-x-hidden">
              {children}
            </main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}